[versions]
mongodb-driver = "4.11.1"
caffeine = "3.1.8"

[libraries]
mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb-driver" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }

[plugins]

[bundles]
