[versions]
commons-lang3 = "3.12.0"
commons-text = "1.11.0"
reflections = "0.9.12"
mapstruct-processor = "1.3.1.Final"
mapstruct = "1.6.0.Beta1"
fastboard = "2.1.5"
adventure-platform-api = "4.3.2"
gson = "2.10.1"

[libraries]
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct-processor" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
fastboard = { module = "fr.mrmicky:fastboard", version.ref = "fastboard" }
adventure-platform-api = { module = "net.kyori:adventure-platform-api", version.ref = "adventure-platform-api" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[bundles]
apache = ["commons-lang3", "commons-text"]
scoreboard = ["fastboard"]
reflections = ["reflections"]

